name: Build

on:
  push:
    branches:
      - '**'  # Cela signifie toutes les branches
  pull_request:
    branches:
      - '**'  # Cela signifie toutes les branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and test Docker image
      run: |
        docker build -t my-project .
        docker run my-project

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Remplacez par la version de .NET que vous utilisez

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with dotnet
      run: dotnet test --no-build --verbosity normal
